# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 06:15
from __future__ import unicode_literals

from django.db import migrations

def createData(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    Category(catName = 'Anti-Biotic')

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createData)
    ]
