# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-29 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_dbData'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
