# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200229_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='itemCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qty', to='inventory.Items'),
        ),
    ]
