# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200229_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='itemCode',
        ),
        migrations.AddField(
            model_name='items',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
